create extension if not exists pgcrypto;

create table if not exists jobs (
  id uuid primary key default gen_random_uuid(),
  job_no text unique,
  source text default 'direct',
  customer_name text,
  customer_phone text,
  customer_phone_masked text,
  customer_note text,
  move_date date,
  scheduled_at timestamptz,
  time_window text,
  start_address text,
  start_address_detail text,
  start_lat numeric,
  start_lng numeric,
  end_address text,
  end_address_detail text,
  end_lat numeric,
  end_lng numeric,
  via_address text,
  via_address_detail text,
  item_summary jsonb default '{}'::jsonb,
  option_summary jsonb default '{}'::jsonb,
  raw_text text,
  price_snapshot jsonb not null default '{}'::jsonb,
  price_version text,
  total_price integer not null default 0,
  deposit_amount integer not null default 0,
  balance_amount integer not null default 0,
  driver_amount integer not null default 0,
  company_amount integer not null default 0,
  status text not null default 'draft',
  dispatch_status text not null default 'idle',
  assigned_driver_id uuid,
  assigned_at timestamptz,
  internal_memo text,
  tags text[] default '{}',
  canceled_at timestamptz,
  canceled_reason text,
  archived_at timestamptz,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
